version: '3.5'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - ./env/.local.db.env
    container_name: postgres
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - '5430:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: nest-docker-postgres
    env_file:
      - ./env/.local.app.env
    ports:
      - '3000:3000'
    depends_on:
      - db
    volumes:
      - ./src:/app/src